#!/bin/bash
mit() {
	[[ $1 == "-r" ]] && depth="" || depth="-maxdepth 1";
	args=($@);
	find . $maxdepth -type d -not -path "*\.git*" -exec sh -c '[ -d "$0"/.git ]' '{}' \; -exec git -C {} "${args[@]:1}" \; -print;
}
mit "$@"
